online_library/online_library/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from book_storage.views import index
from online_library import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_storage.urls')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_library/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'


urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_users, name='logout'),
    path('register/', register_users, name='register'),
    path('profile/', profile, name='profile'),
    path('profile/<int:id_user>/', other_profile, name='other_profile'),
]

online_library/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from random import randint as rn



class User(AbstractUser):
    class GenerateName:
        @classmethod
        def set_name(cls):
            nick = 'user' + ''.join([str(rn(0, 9)) for n in range(10)])
            return nick
    nick = GenerateName.set_name()
    avatar = models.ImageField(upload_to='users/%Y/%m', blank=True, null=True, verbose_name='Аватар')
    nickname = models.CharField(default=nick, max_length=15, verbose_name='Отображаемое имя')
    class Meta:
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

online_library/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2']


class UserEditForm(forms.ModelForm):
    nickname = forms.CharField(label='Логин', widget=forms.TextInput(), max_length=20)
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = get_user_model()
        fields = ('avatar', 'nickname')
        # exclude = ["password"]

online_library/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy

from .forms import LoginUserForm, RegisterUserForm, UserEditForm
from book_storage.models import LikedBook, Book
from .models import User
from global_values import DATA




class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {**DATA, 'title': 'Авторизация'}

    def get_success_url(self):
        return reverse_lazy('home')

def logout_users(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def register_users(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect(reverse('home'))
    else:
        form = RegisterUserForm()
    return render(request, 'users/register.html', {**DATA, 'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            if len(str(form.data.get('nickname')).replace(' ', '')) >= 3:
                form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserEditForm(instance=request.user)
    user_id = request.user.id
    lk_books = LikedBook.objects.filter(user=user_id)
    context = {**DATA, 'title': 'Личный кабинет', 'user': request.user, 'lk_books': lk_books, 'form': form}
    return render(request, 'users/profile.html', context)

def other_profile(request, id_user):
    user_sel = User.objects.get(pk=id_user)
    if request.user.is_authenticated:
        if request.user.username == user_sel.username:
            return HttpResponseRedirect(reverse('users:profile'))
    lk_books = LikedBook.objects.filter(user=id_user)
    context = {**DATA, 'title': 'Профиль', 'user': user_sel, 'lk_books': lk_books}
    return render(request, 'users/other-profile.html', context)

online_library/users/templates/users/login.html
{% extends 'book_storage/base.html' %}
{% load static %}
{% block content %}

<div class="background-form">
<div class="auth-form">
    <div style="display: flex;">
        <h1>Авторизация</h1>
<button type="button" onclick="history.back();">
    <img src="{% static 'book_storage/images/cancel.png' %}">
</button>
    </div>
    <form method="post">
        {% csrf_token %}
        <div>
            <label>Логин</label>
            {{form.username}}
        </div>
        <div>
            <label>Пароль</label>
            {{form.password}}
        </div>
        <div>
            {{form.errors}}
        </div>
        <p><button type="submit">Войти</button></p>
    </form>
    <a href="{% url 'users:register' %}">Нет аккаунта?</a>
</div>
</div>

{% endblock %}

online_library/users/templates/users/other-profile.html
{% extends 'book_storage/base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'book_storage/js/profile.js' %}"></script>
<div class="group-profile">
    <div class="f-group-profile">
    <div class="data-profile">
<h1>Профиль</h1>
    {% if user.avatar %}
    <img src="{{ user.avatar.url }}" width="100px" style="border-radius: 50px">
    {% else %}
    <img src="{% static 'book_storage/images/default.jpg' %}" width="100px" style="border-radius: 50px">
    {% endif %}
<h2>@{{ user.username }}</h2>
<h2>Имя: {{ user.nickname }}</h2><br>
    </div>
<div class="update">
<h2>Изменение данных</h2>
<form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
    <div>{{f}}</div>
    {% endfor %}
    <button type="submit">Изменить</button>
     <button type="button" class="logout-link" onclick="confirmLogout()" data-logout-url="{% url 'users:logout' %}">Выйти из аккаунта</button>
    <a href="{% url 'users:logout' %}" style='color:transparent;'>.</a>
</form></div></div>
<div class="s-group-profile">
    <h3 style="text-align:center">Список отложенных книг</h3> 
    {% if lk_books %}
    <div class="container_books">
        <button class="slider__btn_prev"><img src="{% static 'book_storage/images/arrow-left.jpg' %}" style="width: 16px"></button>
        <div class="books_list">
    {% for lk_book in lk_books %}
        <div class="card-like">
        <a href="{% url 'book_page' lk_book.liked_book.id %}"><img src="{{lk_book.liked_book.book_image.url}}" width="150"></a>
        <a href="{% url 'book_remove' lk_book.id %}">Удалить из списка</a>
        </div>
    {% endfor %}
    </div>
    <button class="slider__btn_next"><img src="{% static 'book_storage/images/arrow-right.jpg' %}" style="width: 16px"></button>
    {% else%}
    <p>У вас нет отложенных книг</p>
    {% endif %}
</div>

<br>


</div>
</div>
{% endblock %}

online_library/users/templates/users/profile.html
{% extends 'book_storage/base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'book_storage/js/profile.js' %}"></script>
<div class="group-profile">
    <div class="f-group-profile">
    <div class="data-profile">
<h1>Профиль</h1>
    {% if user.avatar %}
    <img src="{{ user.avatar.url }}" width="100px" style="border-radius: 50px">
    {% else %}
    <img src="{% static 'book_storage/images/default.jpg' %}" width="100px" style="border-radius: 50px">
    {% endif %}
<h2>@{{ user.username }}</h2>
<h2>Имя: {{ user.nickname }}</h2><br>
    </div>
<div class="update">
<h2>Изменение данных</h2>
<form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for f in form %}
    <div>{{f}}</div>
    {% endfor %}
    <button type="submit">Изменить</button>
     <button type="button" class="logout-link" onclick="confirmLogout()" data-logout-url="{% url 'users:logout' %}">Выйти из аккаунта</button>
    <a href="{% url 'users:logout' %}" style='color:transparent;'>.</a>
</form></div></div>
<div class="s-group-profile">
    <h3 style="text-align:center">Список отложенных книг</h3> 
    {% if lk_books %}
    <div class="container_books">
        <button class="slider__btn_prev"><img src="{% static 'book_storage/images/arrow-left.jpg' %}" style="width: 16px"></button>
        <div class="books_list">
    {% for lk_book in lk_books %}
        <div class="card-like">
        <a href="{% url 'book_page' lk_book.liked_book.id %}"><img src="{{lk_book.liked_book.book_image.url}}" width="150"></a>
        <a href="{% url 'book_remove' lk_book.id %}">Удалить из списка</a>
        </div>
    {% endfor %}
    </div>
    <button class="slider__btn_next"><img src="{% static 'book_storage/images/arrow-right.jpg' %}" style="width: 16px"></button>
    {% else%}
    <p>У вас нет отложенных книг</p>
    {% endif %}
</div>

<br>


</div>
</div>
<button id="showFormSup" >Связаться с поддержкой</button>

<form id="contactForm" class="hidden">
    <div class="form-group">
        <label for="name">Имя:</label>
        <input type="text" id="name" name="name" required>
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
    </div>
    <div class="form-group">
        <label for="message">Сообщение:</label>
        <textarea id="message" name="message" required></textarea>
    </div>
    <button type="submit">Отправить</button>
</form>
{% comment %} <a class="support" href="#">Связаться с поддержкой</a> {% endcomment %}
{% endblock %}

online_library/users/templates/users/register.html
{% extends 'book_storage/base.html' %}
{% load static %}
{% block content %}
<style>
    .footer{display: none}
 </style>
<div class="background-form">
    <form class="registration-form" method="post">
        <div style="display: flex;">
        <h1 class="registration-title">Регистрация</h1>
        <button type="button" onclick="history.go(-2);">
            <img src="{% static 'book_storage/images/cancel.png' %}">
        </button>
    </div>
        {% csrf_token %}
        <div>
            <label class="registration-label">Логин</label>
            {{form.username}}
        </div>
        <div>
            <label class="registration-label">Пароль</label>
            {{form.password1}}
        </div>
        <div>
            <label class="registration-label">Пароль ещё раз</label>
            {{form.password2}}
        </div>
        <div>
            {{form.username.errors}}
            {{form.password2.errors}}
        </div>

        <p><button class="registration-button" type="submit">Сохранить</button></p>
        <a class="registration-link" href="{% url 'users:login' %}">Есть аккаунт?</a>
    </form>
</div>
{% endblock %}