online_library/book_storage/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('genre/<int:id_genre>', home, name='home_genre'),
    path('type/<int:type_of_book>', home, name='home_type'),
    path('book/<int:id_book>/', book_page, name='book_page'),
    path('book/add/<int:id_book>/', add_liked_book, name='book_add'),
    path('book/remove/<int:id_lk_book>/', remove_liked_book, name='book_remove'),
    path('book-read/<int:id_book>/', read_page, name='read_page'),
    path('author/<int:id_author>/', author_page, name='author_page'),
    path('authors/', authors_page, name='authors_page'),
    path('about/', about_page, name='about'),
    path('book/<int:id_book>/rating/<int:value>/', add_book_rating, name='book_rating_change'),
    path('book/<int:id_book>/comment/', book_comments, name='book_comment'),
    path('book/comment/<int:id_comment>', delete_comment, name='delete_comment'),
    path('search/', search, name='search'),
    path('tags/', tags_page, name='tags_page'),
    path('generate/<path:book_search>/', generate, name='generate'),
    path('generate-create/<path:book_url>/', create_generated_book, name='generate_create'),
]

online_library/online_library/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from book_storage.views import index
from online_library import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_storage.urls')),
    path('users/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_library/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'


urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_users, name='logout'),
    path('register/', register_users, name='register'),
    path('profile/', profile, name='profile'),
    path('profile/<int:id_user>/', other_profile, name='other_profile'),
]

online_library/book_storage/models.py
import string, random as rnd

from django.db import models
import string, random as rnd

from django.db import models
from users.models import User

class Author(models.Model):
    fio_author = models.CharField(max_length=50, verbose_name='ФИО автора')
    biography = models.TextField(max_length=2100, verbose_name='Биография')
    photo = models.ImageField(upload_to=f"authors/avatar", blank=True, verbose_name='Фотография')

    def __str__(self):
        return self.fio_author

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        ordering = ['fio_author',]


class Publisher(models.Model):
    publisher_name = models.CharField(max_length=50, verbose_name='Названия издательства')

    def __str__(self):
        return self.publisher_name

    class Meta:
        verbose_name = 'Издатель'
        verbose_name_plural = 'Издатели'


class Genre(models.Model):
    genre = models.CharField(max_length=50, verbose_name='Жанр')

    def __str__(self):
        return self.genre

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class TypeOfBook(models.Model):
    type_of_book = models.CharField(max_length=50, verbose_name='Тип книги')

    def __str__(self):
        return self.type_of_book

    class Meta:
        verbose_name = 'Тип книги'
        verbose_name_plural = 'Тип книг'


class BookSeries(models.Model):
    book_series = models.CharField(max_length=35, verbose_name='Название цикла')
    class Meta:
        verbose_name = 'Цикл книг'
        verbose_name_plural = 'Циклы книг'

    def __str__(self):
        return self.book_series

class Book(models.Model):
    class Helper:
        @classmethod
        def create_file_path(cls):
            file_path = ''
            for _ in range(6):
                file_path += string.ascii_lowercase[rnd.randint(0, len(string.ascii_lowercase)-1)]
                file_path += str(rnd.randint(0, 9))
            return file_path

    file_path = Helper.create_file_path()
    title = models.CharField(max_length=50, verbose_name='Название')
    id_author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')  # few authors
    book_series = models.ForeignKey(BookSeries, on_delete=models.PROTECT, null=True, blank=True, verbose_name='Цикл')
    book_ind = models.SmallIntegerField(verbose_name='Номер в цикле', default=0)
    writing_year = models.IntegerField(verbose_name='Год написания')
    id_publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, verbose_name='Издатель')
    id_genre = models.ManyToManyField(Genre, verbose_name='Жанры')
    type_of_book = models.ForeignKey(TypeOfBook, on_delete=models.CASCADE, verbose_name='Тип книги')
    description = models.TextField(max_length=1250, verbose_name='Описание')
    read_text = models.TextField(verbose_name='Содержание книги')
    book_image = models.ImageField(upload_to=f"books/%Y/%m{file_path}", verbose_name='Обложка книги')
    fb2_path = models.FileField(upload_to=f"books/%Y/%m{file_path}", verbose_name='fb2 файл')
    epub_path = models.FileField(upload_to=f"books/%Y/%m{file_path}", blank=True, verbose_name='epub файл')
    mp3_path = models.FileField(upload_to=f"books/%Y/%m{file_path}", blank=True, verbose_name='mp3 файл')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    VERIFIED_STATUS = [(False, 'Не проверено'), (True, 'Проверено')]
    is_verified = models.BooleanField(choices=VERIFIED_STATUS, default=False, verbose_name='Модерация')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ['-rating', 'time_update', 'title']

    def __str__(self):
        return self.title


class LikedBook(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    liked_book = models.ForeignKey(to=Book, on_delete=models.CASCADE)

    def __str__(self):
        return f'Отложенная книга {self.liked_book.title} для {self.user.username}'

class BookRating(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    book = models.ForeignKey(to=Book, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created',]

    def __str__(self):
        return f'Комментарий {self.user} к книге: {self.book}'

online_library/book_storage/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text',]

online_library/book_storage/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from .forms import CommentForm
from .models import *
from django.views.decorators.http import require_POST
from django.db.models import Q
from global_values import DATA
import parse
import asyncio

def home(request, id_genre=None, type_of_book=None):
    if id_genre:
        books = Book.objects.filter(id_genre=id_genre, is_published=True)
        message = f'Все книги с жанром: {Genre.objects.get(pk=id_genre)}'
    elif type_of_book:
        books = Book.objects.filter(type_of_book=type_of_book, is_published=True)
        message = f'Все книги с тегом: {TypeOfBook.objects.get(pk=type_of_book)}'
    else:
        books = Book.objects.filter(is_published=True)
        message = ''
    genres = Genre.objects.all()
    types = TypeOfBook.objects.all()
    paginator = Paginator(books, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {**DATA, 'title': 'Главная', 'books': books, 'message': message, 'page_obj': page_obj}
    return render(request, 'book_storage/index.html', context)


def book_page(request, id_book):
    book = Book.objects.get(pk=id_book)  # выбор книги по id
    ser_books = False
    if book.book_series:
        ser = book.book_series
        ser_bks = Book.objects.filter(book_series=ser)
        ser_books = []
        for b in ser_bks:
            ser_books.append(
                [b.book_ind,
                {'title': b.title, 'pk': b.pk}
                 ])
        try:
            ser_books.sort()
        except:
            pass
        ss = [sb[-1] for sb in ser_books]
        ser_books = ss
    genres = book.id_genre.all()
    author = book.id_author
    rate = 0
    if request.user.is_authenticated:
        rate = BookRating.objects.filter(user=request.user, book=book)
        if rate.exists():
            rate = BookRating.objects.get(user=request.user, book=book)
            rate = rate.rating
    comments = Comment.objects.filter(book=id_book, active=True)
    form = CommentForm  # ()
    check = False
    if request.user.is_authenticated:
        user = request.user
        check_comment = Comment.objects.filter(book=id_book, user=user)
        check = not bool(check_comment)

    data = {**DATA, 'title': f'Книга {book.title}', 'book': book, 'genres': genres, 'author': author,
            'ser_books': ser_books, 'rate': rate, 'comments': comments, 'form': form, 'check': check}
    return render(request, 'book_storage/book_page.html', data)


def author_page(request, id_author):
    author = Author.objects.get(pk=id_author)
    all_books = Book.objects.filter(id_author=id_author)
    serias_books, books = set(), []
    for b in all_books:
        if b.book_series != None:
            serias_books.add(b.book_series)
        else:
            books.append(b)
    books_in_seria = []
    for b in serias_books:
        try:
            seria = BookSeries.objects.get(book_series=b.book_series)
            books_in_seria.append(Book.objects.filter(book_series=seria))
        except:
            pass
    data = {**DATA, 'title': f'Страница автора', 'author': author, 'books': books, 'books_in_seria': books_in_seria}
    return render(request, 'book_storage/author_page.html', data)


def authors_page(request):
    authors = Author.objects.all()
    books = Book.objects.all()
    data = {**DATA, 'title': f'Все авторы', 'authors': authors}
    return render(request, 'book_storage/authors_page.html', data)


@login_required
def add_liked_book(request, id_book):
    book = Book.objects.get(pk=id_book)
    lk_book = LikedBook.objects.filter(user=request.user, liked_book=book)
    if not lk_book.exists():
        LikedBook.objects.create(user=request.user, liked_book=book)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def remove_liked_book(request, id_lk_book):
    lk_book = LikedBook.objects.get(pk=id_lk_book)
    lk_book.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def read_page(request, id_book):
    book = Book.objects.get(pk=id_book)
    data = {**DATA, 'title': f'{book.title}', 'book': book}
    return render(request, 'book_storage/read_page.html', data)


def about_page(request):
    context = {**DATA, 'title': 'Кто мы?'}
    return render(request, 'book_storage/about.html', context)


@login_required
def add_book_rating(request, id_book, value):
    if value == 1:
        value = 1
    elif value == 2:
        value = -1
    else:
        value = 0
    book = Book.objects.get(pk=id_book)
    book_rating = BookRating.objects.filter(user=request.user, book=book)
    if not book_rating.exists():
        BookRating.objects.create(user=request.user, book=book, rating=value)
        book.rating += value
        book.save()
    else:
        book_rating = BookRating.objects.get(book=book, user=request.user)
        if book_rating.rating != value:
            book_rating.rating = value
            book_rating.save()
            book.rating += (value * 2)
            book.save()
    uri = reverse('book_page', args=(id_book,))
    return redirect(uri)


def book_comments(request, id_book):   # try to del
    book1 = Book.objects.get(pk=id_book)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            text = form.data.get('text')
            Comment.objects.create(user=request.user, book=book1, text=text)
            uri = reverse('book_page', args=(id_book,))
            return redirect(uri)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'book_storage/comment.html', context)


@login_required
def delete_comment(request, id_comment):
    comment = Comment.objects.get(pk=id_comment)
    id_book = comment.book.id
    uri = reverse('book_page', args=(id_book,))
    if request.user == comment.user:
        comment.delete()
    return redirect(uri)


def search(request):
    search_quary = request.GET.get('search-all', '')
    if search_quary:
        books = Book.objects.filter(Q(title__icontains=search_quary) | Q(description__icontains=search_quary),
                                    is_published=True)
        authors = Author.objects.filter(fio_author__icontains=search_quary)
        # seria = BookSeries.objects.filter(book_series__icontains=search_quary)
    else:
        return HttpResponseRedirect(reverse('home'))

    data = {**DATA, 'title': 'Результаты поиска', 'books': books, 'authors': authors, 'search_quary_': search_quary}
    return render(request, 'book_storage/search_page.html', data)


def tags_page(request):  # try to del
    genres = Genre.objects.all()
    types = TypeOfBook.objects.all()
    data = {'title': 'Выбрать книгу', 'genres': genres, 'types': types, }
    return render(request, 'book_storage/tags_page.html', data)

def generate(request, book_search):
    search_quary = book_search
    if search_quary:
        loop = asyncio.new_event_loop()
        res = loop.run_until_complete(parse.main(search_quary))
        #return HttpResponse('res:', res)
        data = {**DATA, 'resources': res}
        return render(request, 'book_storage/generate_page.html', data)


def create_generated_book(request, book_url):
    loop = asyncio.new_event_loop()
    res = loop.run_until_complete(parse.download_book(book_url))
    if Author.objects.filter(fio_author=res['author']).exists():
        current_author = Author.objects.get(fio_author=res['author'])
    else:
        res_author = loop.run_until_complete(parse.author_parse(res['author_url']))
        current_author = Author.objects.create(fio_author=res_author['author_fio'], biography=res_author['bio'], photo=res_author['img'])
    if res['seria']:
        if BookSeries.objects.filter(book_series=res['seria']).exists():
            current_seria = BookSeries.objects.get(book_series=res['seria'])
        else:
            current_seria = BookSeries.objects.create(book_series=res['seria'])
    else:
        current_seria = None


    book = Book.objects.create(title=res['title'], id_author=current_author, book_series=current_seria, writing_year=res['year'],
                               id_publisher=Publisher.objects.get(pk=1),
                               type_of_book=TypeOfBook.objects.get(pk=4), description=res['description'], read_text='Не сгенерировано',
                               book_image=res['img'], fb2_path=res['fb2'], epub_path=res['epub'])
    for tag in res['tags']:
        if not Genre.objects.filter(genre=tag).exists():
            current_tag = Genre.objects.create(genre=tag)
        else:
            current_tag = Genre.objects.get(genre=tag)
        book.id_genre.add(current_tag)
    uri = reverse('book_page', args=(book.pk,))
    return redirect(uri)


    #return HttpResponse(f'text: {book_url}\nAuthor --> exists\nres = {res}')

online_library/book_storage/templates/book_storage/authors_page.html
{% extends 'book_storage/base.html' %}
{% load static %}

{% block content %}
<script src="{% static 'book_storage/js/authors_page.js' %}"></script>
<div class="container-authors">
{% for author in authors %}
<div class="card-author">
    {% if author.photo %}
    <a href="{% url 'author_page' author.id %}">
        <img src="{{ author.photo.url }}" alt="{{ author.fio_author }} photo" height='250px' style='border-radius:20px'></a>
    {% else %}
    <a href="{% url 'author_page' author.id %}"><img src="{% static 'book_storage/images/default.jpg' %}"alt="Default photo" height='250px' style='border-radius:20px'></a>
    {% endif %}
<div data-biography="{{ author.biography }}" data-page-url="{% url 'author_page' author.id %}" class="author_info">

    <h1><a href="{% url 'author_page' author.id %}">{{ author.fio_author }}</a></h1>

  </div>
</div>

{% endfor %}
</div>
{% endblock %}

online_library/book_storage/templates/book_storage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'book_storage/images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'book_storage/css/style.css' %}">
    <script src="{% static 'book_storage/js/base.js' %}"></script>
    <title>{{ title }}</title>
</head>
<body>
    <div class="wrapper">
{% block main_menu %}
<header class="back_head" style="background-color: #333;">
<div class="header">
    <div class="logo">
        <a  href="{% url 'home'  %}">
        <img src="{% static 'book_storage/images/logo.png' %}">
        </a>
    </div>
    <nav class="main-nav">

        <ul>

            <li><button type="button" onclick="showModal()">Жанры</button></li>
            {% for elem in menu %}
            <li><a href="{% url elem.1  %}">{{ elem.0 }}</a></li>
            {% endfor %}
        </ul>
    </nav>
    <form action="{% url 'search' %}">
    <div class="header_search">
        <input type="search" class="header_search_input" placeholder="Искать" value="" name="search-all">
        <button type="submit" class="header_search_button">Найти</button>
    </div>
</form>
    <figure>
        <a href="{% url 'users:profile' %}">
            {% if request.user.is_authenticated and request.user.avatar%}
                    <img src="{{ request.user.avatar.url }}" width="50px" style="border-radius: 50px">
            {% else %}
            <img src="{% static 'book_storage/images/default.jpg' %}" width = "50px" style="border-radius: 50px" >
            {% endif %}
        </a>
    </figure>
</div>
<div class="dialog-overlay" onclick="hideModal()">
    <div class="dialog-content" onclick="event.stopPropagation()">
        <div class="gen">
            <h4>Жанры</h4>
            {% for genre_all in genres_all|slice:":10" %}
                <a href="{% url 'home_genre' genre_all.id %}">{{ genre_all.genre }}</a><br>
            {% endfor %}
        </div>
        <div class="type">
            <h4>Тип книг</h4>
            {% for type_all in types_all|slice:":10" %}
                <a href="{% url 'home_type' type_all.id %}">{{ type_all.type_of_book }}</a><br>
            {% endfor %}
        </div>
            <a href="{% url 'tags_page' %}">Все теги</a>
    </div>
</div>
</header>
{% endblock main_menu %}
<main class="content">

{% block content %}

{% endblock %}
</main>
<footer class="back_head" style="background-color: #333;">
 <div class="footer">
    <p>Online library. Все права не защищены.</p>   
 </div></footer>
</div>
</body>
</html>

online_library/book_storage/templates/book_storage/book_page.html
{% extends 'book_storage/base.html' %}
{% load static %}

{% block content %}
<script src="{% static 'book_storage/js/book_page.js' %}"></script>
<div class="layout_book">

    <div class="FunctionalBlock">
        <ul>
            <li>
                <button type="button" class="FunctionalBlock_button" id="button_save" onclick="alert(`Книга {{ book.title }} отложена`)">
                    <div class="button">
                        <span class="FunctionalBlock_save_icon">❤</span>
                        <span class="FunctionalBlock_save_text"><a
                                href="{% url 'book_add' book.id %}">Отложить</a>></span>
                    </div>
                </button>
                <button type="button" class="FunctionalBlock_button" id="button_readen">
                    {% comment %}
                    <div class="button">
                        <span class="FunctionalBlock_icon">✓</span>
                        <span class="FunctionalBlock_save_text">Отметить прочитанным</span>
                    </div>
                </button>
                {% endcomment %}
                <button type="button" onclick="showModal()"class="FunctionalBlock_button" id="copyButton">
                    <div class="button">
                        <span class="FunctionalBlock_icon_copy">🔗</span>
                        <span class="FunctionalBlock_save_text">Поделиться</span>
                    </div>
                </button>
        </ul>
        <div id="copyForm">
            <input type="button" value="Скопировать ссылку" onclick="Copy();" />
            <textarea id="url" rows="1" cols="30"></textarea>
            <button type="button" onclick="history.go(0);">
                <img src="{% static 'book_storage/images/cancel.png' %}" width=45px>
            </button>
        </div>
    </div>
    <div class="book_main">
        <div class="left_info">
            <div class="book_scroll">
            <img src="{{ book.book_image.url }}">
            {% if book.rating > 0 %}
            <div class="rate-green" style="height: 5px; width: 180px; background-color: green"></div>
            {% elif book.rating < 0 %}
            <div class="rate-red" style="height: 5px; width: 180px; background-color: red"></div>
            {% else %}
            <div class="rate-grey" style="height: 5px; width: 180px; background-color: grey"></div>
            {% endif %}
            <br>
            <a href="{% url 'read_page' book.id %}" class="read_fragment">Читать фрагмент</a>
        </div></div>
        <div class="center_info">
            <div>
                <h1 id="book_title">{{ book.title }}</h1>
                {% if book.is_verified %}
                    <img src="{% static 'book_storage/images/true.png' %}" width="25px">
                {% else %}
                    <img src="{% static 'book_storage/images/false.png' %}" width="25px">
                {% endif %}
            </div>

            <div class="type_book">
                {% if book.mp3_path %}
                <img src="{% static 'book_storage/images/text_audio.svg' %}" alt="Изображение">
                <div>текст и аудиокнига</div>
                {% else %}
                <img src="{% static 'book_storage/images/text.svg' %}" alt="Изображение">
                <div>текст</div>
                {% endif %}
            </div>
            <div class="seriya">
                {% if book.book_series %}
                <p>Входит в серию <b>{{ book.book_series }}</b>:</p>
                {% if ser_books %}
                <button onclick="show_seria()"
                        style="color: blue; font: normal 14px/20px ALS Sirius,Arial,Helvetica Neue,Helvetica,sans-serif;">
                    Посмотреть содержимое
                </button>
                <div class="sh_books" style="display: none;">
                    {% for bk in ser_books %}
                    <a href="{% url 'book_page' bk.pk %}">{{ bk.title }}</a><br>
                    {% endfor %}
                </div>
                {% endif %}
                {% else %}
                <p>Данная книга не входит в цикл книг</p>
                {% endif %}
            </div>
            <h3>Автор</h3>
            <div class="author"><a href="{% url 'author_page' book.id_author.id %}">
                {% if author.photo %}
                <img src="{{ author.photo.url }}" , width="40px">
                {% else %}
                <img src="{% static 'book_storage/images/default.jpg' %}" , width="40px">
                {% endif %}</a>
                <a href="{% url 'author_page' book.id_author.id %}">{{ book.id_author }}</a></div>
            <br>
            <p>Рейтинг: {{ book.rating }}</p>
            {% if rate == 1 %}
            <a href="{% url 'book_rating_change' book.id 1 %}"><img
                    src="{% static 'book_storage/images/like-selected.png' %}" width="25px"></a>
            {% else %}
            <a href="{% url 'book_rating_change' book.id 1 %}"><img src="{% static 'book_storage/images/like.png' %}"
                                                                    width="25px"></a>
            {% endif %}
            {% if rate == -1 %}
            <a href="{% url 'book_rating_change' book.id 2 %}"><img
                    src="{% static 'book_storage/images/dislike-selected.png' %}" width="25px"></a>
            {% else %}
            <a href="{% url 'book_rating_change' book.id 2 %}"><img src="{% static 'book_storage/images/dislike.png' %}"
                                                                    width="25px"></a>
            {% endif %}
            <h3>Теги</h3>
            <div class="genres">
                <a href="{% url 'home_type' book.type_of_book.id %}">{{ book.type_of_book }}</a>
                {% for genre in genres %}
                <a href="{% url 'home_genre' genre.id %}">{{ genre }}</a>
                {% endfor %}
            </div>
            <div class="date_of_writing">
                <h3>Дата написания</h3></div>
            {{ book.writing_year }}
            <div class="publisher">
                <h3>Издатель</h3>
                <p>{{ book.id_publisher }}</p>
            </div>

            <div class="description">
                <h3>Описание</h3>
                <p>{{ book.description }}</p>
            </div>
             <div>
                 <br>
                {% if book.is_verified %}
                <img src="{% static 'book_storage/images/true.png' %}" width="30px">
                <p>Данная книги проверена администрацией.</p>
                {% else %}
                <img src="{% static 'book_storage/images/false.png' %}" width="30px">
                <p>Данная книга не проходила провеку администрации.</p>
                <p>Это значит, что эта страница была сгенерирована по запросу пользователей, и содержание этой страницы
                    может быть искажено. Если вы нашли ошибку или вы захотели пожаловаться на книгу, то перейдите
                <a href="#">По этой ссылке</a> чтобы связаться с администрацией.</p>
                {% endif %}
            </div>
            {% if request.user.is_authenticated %}
            {% if check %}
            {% include 'book_storage/includes/comment_form.html' %}
            {% endif %}
            {% else %}
            <h4>Чтобы оставить комментарий, <a href="{% url 'users:login' %}">авторизируйтесь</a></h4>
            {% endif %}


            <div class="comments">
                {% with comments.count as total_comments %}
                <h3>{{ total_comments }} комментариев</h3>
                {% endwith %}
                {% for comment in comments %}
                <div class="comment">
                    <div class="comment-profile">
                    {% if comment.user.avatar %}
                    <a href="{% url 'users:other_profile' comment.user.id %}"><img src="{{ comment.user.avatar.url }}" width="50px"></a>
                    {% else %}
                    <a href="{% url 'users:other_profile' comment.user.id %}"><img src="{% static 'book_storage/images/default.jpg' %}" width="100px"></a>
                    {% endif %}
                    <a href="{% url 'users:other_profile' comment.user.id %}">{{ comment.user.nickname }}</a>
                    </div>
                    {{ comment.text|linebreaks }}
                    {% if request.user.is_authenticated %}
                        {% if request.user.id == comment.user.id %}
                            <a class="comment-delete" href="{% url 'delete_comment' comment.id %}">Удалить</a>
                        {% endif %}
                    {% endif %}
            
                </div>
                {% empty %}
                <p>Здесь нет комментариев. Вы можете стать первым!</p>
                {% endfor %}
            </div>


        </div>
        <div class="right_info">
            <div class="download_links">
            <p><a class="fb2" href="{{ book.fb2_path.url }}">Скачать FB2</a></p>
            {% if book.epub_path %}
            <p><a class="epub" href="{{ book.epub_path.url }}">Скачать EPUB</a></p>
            {% endif %}
            {% if book.mp3_path %}
            <p><a class="mp3" href="{{ book.mp3_path.url }}">Скачать MP3</a></p>
            {% endif %}
        </div>
    </div>
    </div>
</div>


{% endblock %}

online_library/book_storage/templates/book_storage/generate_page.html
{% extends 'book_storage/base.html' %}
{% load static %}
{% block content %}
<style>
    .card{
        height: 380px;
    }
</style>
<h2>Книги по вашему запросу</h2>
<div class="products">
{% for res in resources %}
<div class="card">

<a href="{% url 'generate_create' res.url %}">
    <img src="{{res.img}}">
    <p>{{ res.title }}</p></a>
<p>{{ res.author }}</p>

</div>

{% empty %}
<p>По вашему запросу мы не смогли найти книги</p>
{% endfor %}
</div>
<a class="home" href="{% url 'home' %}">На главную</a>



{% endblock %}